# netlify.toml

[build]
  publish = "/"
  functions = "netlify/functions"

# 基础的函数配置
[functions]
  node_bundler = "esbuild"

# 新方法：只为会超时的 huggingface-image 函数单独设置超时
[functions.huggingface-image]
  timeout = 60 # 将这个函数的超时时间延长到 60 秒

# 为AI对话功能也设置一个长一点的超时，以防万一
[functions.gemini]
  timeout = 30 # 将这个函数的超时时间延长到 30 秒

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  # 新增这条规则来代理图片请求
[[redirects]]
  from = "/.netlify/images"
  to = "https://images.unsplash.com" # 只是一个占位符，实际会动态替换
  status = 200
  force = true
  [redirects.query]
    url = ":url"